name: Eldono de EO IME

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write
    
    steps:
      - name: Elpreni la kodon.
        uses: actions/checkout@v7

      - name: Akiri versian numeron.
        id: versio
        shell: bash
        run: |
          # Eltiri versian numeron el Cargo.toml.
          echo "versio=$(grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)".*/\1/')" >> $GITHUB_OUTPUT

      - name: Agordi Rust-on.
        uses: dtolnay/rust-toolchain@stable

      - name: Konstrui eldonan version.
        run: cargo build --release
      
      - name: Krei eldonon kaj alŝuti.
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: EO IME v${{ steps.versio.outputs.versio }}
          tag_name: v${{ steps.versio.outputs.versio }}
          files: target/release/eo_ime.exe
          prerelease: false
          body: |
            ## 🔧 修复更新

            - 修复cĉ问题
            - 回写替换
            - 修复无法大写问题
            - 修复大写延时导致变成小写
            - 修复无法进入shift的问题
            - 修复shift无法归位问题
